### ISSUE TITLE
Better Episode support?

### ISSUE THREAD

**Issue by go2tom42** [kemalyazici/shortcode-imdb#1]
this shortcode `[imdb style="white"]tt5696852[/imdb]`generates 
![27o0ciz](https://user-images.githubusercontent.com/12462792/50240676-5e60f880-0393-11e9-91d7-6215b19b8e50.png)

Would it be possible to remove the "Episode aired 23 December 2016" and also include the series name.  Maybe something like this
![27o0ciz2](https://user-images.githubusercontent.com/12462792/50241531-b26cdc80-0395-11e9-82c8-d4ce18c84a50.png)

**Comment by kemalyazici** [comment]
Yeah, nice issue. I'm gonna work on it.  Soon publish an update...

**Comment by kemalyazici** [comment]
I've published v.2.4... So it's updated as you wish.... Cheers...

**Comment by go2tom42** [comment]
New Request: Ability to change "img" url in cache?

When doing episodes the default imdb picked image is normally useless, I've been directly editing the DB with myphpadmin.  Example

I edit the cache for the episode entry under wp_shortcode_imdb_cache
I change this 
`"img":"https:\/\/m.media-amazon.com\/images\/M\/MV5BYjljYTMxZTEtODI5ZC00NDNmLTk2YzMtYzJmZWUyOTA4Y2UzXkEyXkFqcGdeQXVyMjMxMzE4OTQ@._V1_UY99_CR50,0,99,99_AL_.jpg"},`
to something like this
`"img":"https:\/\/mysite.com\/folder\/pics\/image.jpg"},`

Any way you could make that an option in the plugin without to much work?

**Comment by kemalyazici** [comment]
Hi.. Editing cache will come with version 3 updates. It's on my "to do list" already. You will be able to full edit the cache....

**Comment by kemalyazici** [comment]
Hi, version 3.0 is live now.
